service:
  internalPort: 8000
  externalPort: 8000
ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - synthesis'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
  tls:
    secretName: this-is-synthesis
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 60
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 60
nodeSelector:
  type: lda
postgresql:
  managed: false
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "4500Mi"
    cpu: "1500m"
